
apiVersion: v1
kind: Service
metadata:
  name: project001

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: project001

  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
